# Generated by Django 5.0.6 on 2024-07-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_height', models.IntegerField()),
                ('patient_weight', models.IntegerField()),
                ('patient_history', models.BooleanField()),
                ('patient_scan_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='us_scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('coordinates', models.CharField(max_length=5)),
                ('scanDate', models.DateField()),
                ('diagnosis', models.CharField(verbose_name=15)),
            ],
        ),
    ]
