# Generated by Django 5.0.6 on 2024-07-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientAge', models.IntegerField()),
                ('PatientHeight', models.IntegerField()),
                ('PatientWeight', models.IntegerField()),
                ('PatientHistory', models.BooleanField()),
                ('PatientUSScanID', models.IntegerField()),
                ('PatientCoordinates', models.CharField(max_length=5)),
                ('PatientScanDate', models.DateField()),
                ('PatientDiagnosis', models.CharField(verbose_name=15)),
            ],
        ),
    ]
