# Generated by Django 5.0.6 on 2024-07-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_history',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_weight',
            field=models.CharField(max_length=10),
        ),
    ]
