# Generated by Django 5.0.6 on 2024-07-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0002_alter_patients_patient_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_scan_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_weight',
            field=models.IntegerField(),
        ),
    ]
