# Generated by Django 5.0.6 on 2024-07-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0003_alter_patients_patient_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_scan_id',
            field=models.CharField(max_length=50),
        ),
    ]
