# Generated by Django 5.0.6 on 2024-07-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0004_alter_patients_patient_scan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us_scans',
            old_name='scanDate',
            new_name='scan_date',
        ),
    ]
