# Generated by Django 5.0.6 on 2024-07-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0005_rename_scandate_us_scans_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_scan_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
