# Generated by Django 5.0.6 on 2024-07-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0006_alter_patients_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_scan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
