# Generated by Django 5.0.6 on 2024-07-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0007_alter_patients_patient_scan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us_scans',
            name='id',
        ),
        migrations.AlterField(
            model_name='us_scans',
            name='scan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
