# Generated by Django 5.0.6 on 2024-07-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0008_remove_us_scans_id_alter_us_scans_scan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=5)),
                ('password', models.DateField()),
            ],
        ),
    ]
