# Generated by Django 5.0.6 on 2024-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0010_alter_admin_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_users',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
