# Generated by Django 5.0.6 on 2024-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientSystem', '0011_alter_admin_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin_users',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='admin_users',
            name='user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
